@startuml PerformUpdateIfNecessary
:**PerformUpdateIfNecessary**|
:**assert it should be in its own update batch to reduce update**;
fork
  :**is root react component update?**
  Noninitial ReactDOM.render() might enqueue 
  _pendingElement to update root component;
  :**update children**
  GO __Receive Component__;
fork again
  :**is caused by setState or forceUpdate?**;
  :**GO __Update Component__;
end fork
@enduml