@startuml Mount
:ReactDOM.render(<App />, container)/
:Enter DefaultBatchingStrategyTransaction
Wrappers
- FLUSH_BATCHED_UPDATES: ( , flush updates)
- RESET_BATCHED_UPDATES: ( , reset isBatchingUpdates status to false)>
:Enter ReconcileTransaction
Wrappers
- SELECTION_RESTORATION: (record selection, restore selection)
- EVENT_SUPPRESSION: (disable BrowserEventEmitter, reset to previous status)
- ON_DOM_READY_QUEUEING: (reset DidMount/DidUpdate callback queue, notify all callbacks)>
:**generate the corresponding DOM Tree of <App />**;
:**insert the tree to the container**;
:Leave ReconcileTransaction<
:Leave ReconcileTransaction<
stop
@enduml